### ISSUE TITLE
Ask the user whether they want to open the site

### ISSUE THREAD

**Issue by slaFFik** [andrewjmead/wpsites#37]
Right now `wpsites` defaults to opening a site in a browser.

What about asking the user "Do you want to open the site in the browser?" with a default value Yes, but with ability to either `enter` or type `y` and `enter` to open, or type `n` to not open it.

**Comment by andrewjmead** [comment]
I'm down for that. Will add.

**Comment by andrewjmead** [comment]
I added a new top-level option `should_open_new_site` that can be set to `false` to stop WPSites from attempting to open new sites in the browser. It's in 1.10.0.
