### ISSUE TITLE
Output full site path in terminal after site creation

### ISSUE THREAD

**Issue by slaFFik** [andrewjmead/wpsites#38]
After the site creation I'm quite often (but not always) want to open it in the editor/IDE (like zed, subl, phpstorm).

What do you think about printing the full site path in the terminal? No need to do anything else, just print the full path:

```
Site path: /home/slaffik/Projects/one/example.test
```
And then the developer will decide whether they want to copy the path and run their IDE from the cli like `zed /home/slaffik/Projects/one/example.test` or something.

**Comment by andrewjmead** [comment]
Love it. I'll add that.

**Comment by andrewjmead** [comment]
@slaFFik The directory is already logged out. Can you confirm?

**Comment by andrewjmead** [comment]
Never mind. I was looking at code I hadn't committed where I added it 🤦‍♂️

**Comment by andrewjmead** [comment]
Added in 1.10.0!
